/// Complete exercise database with YouTube video IDs
class Exercise {
  final String id;
  final String nameAr;
  final String nameEn;
  final String muscleGroup;
  final String secondaryMuscles;
  final String difficulty;
  final String equipment;
  final String youtubeVideoId;
  final String description;
  final String formTips;
  final List<String> muscleActivation;

  const Exercise({
    required this.id,
    required this.nameAr,
    required this.nameEn,
    required this.muscleGroup,
    this.secondaryMuscles = '',
    required this.difficulty,
    required this.equipment,
    required this.youtubeVideoId,
    required this.description,
    required this.formTips,
    this.muscleActivation = const [],
  });
}

class ExerciseDatabase {
  static const List<Exercise> allExercises = [
    // ═══════════════════════════════════════════════════════════
    // CHEST EXERCISES
    // ═══════════════════════════════════════════════════════════
    Exercise(
      id: 'bench_press',
      nameAr: 'بنش بريس مسطح',
      nameEn: 'Barbell Bench Press',
      muscleGroup: 'صدر',
      secondaryMuscles: 'ترايسبس، أكتاف',
      difficulty: 'متوسط',
      equipment: 'باربل',
      youtubeVideoId: 'vcBig73ojFE',
      description: 'تمرين أساسي لبناء عضلة الصدر مع استخدام الباربل',
      formTips: 'حافظ على استقامة الكتفين والظهر، اضغط بشكل متحكم，不要锁死关节',
      muscleActivation: ['الصدر العلوي', 'الصدر الأوسط', 'الترايسبس'],
    ),
    Exercise(
      id: 'incline_bench_press',
      nameAr: 'بنش بريس مائل',
      nameEn: 'Incline Bench Press',
      muscleGroup: 'صدر',
      secondaryMuscles: 'ترايسبس، أكتاف',
      difficulty: 'متوسط',
      equipment: 'باربل',
      youtubeVideoId: 'SrWfCXh2RZc',
      description: 'يستهدف الجزء العلوي من عضلة الصدر',
      formTips: 'اضبط زاوية المقعد إلى 30-45 درجة، حافظ على مرفقين بزاوية 90 درجة',
      muscleActivation: ['الصدر العلوي', 'الصدر الأوسط'],
    ),
    Exercise(
      id: 'dumbbell_fly',
      nameAr: 'ديد بنش بالدمبل',
      nameEn: 'Dumbbell Fly',
      muscleGroup: 'صدر',
      secondaryMuscles: 'صدر أمامي',
      difficulty: 'سهل',
      equipment: 'دمبل',
      youtubeVideoId: 'eozdVDA78K0',
      description: 'تمرين عزل للصدر يفتح ويغلق الذراعين',
      formTips: 'حافظ على انحناء خفيف في المرفقين، اقلب الاتجاه في النهاية',
      muscleActivation: ['الصدر الخارجي', 'الصدر الداخلي'],
    ),
    Exercise(
      id: 'cable_fly',
      nameAr: 'كيبل فلاي',
      nameEn: 'Cable Fly',
      muscleGroup: 'صدر',
      secondaryMuscles: 'صدر أمامي',
      difficulty: 'سهل',
      equipment: 'كيبل',
      youtubeVideoId: 'Iwe6AmxVf7o',
      description: 'تمرين كيبل لعزل عضلة الصدر',
      formTips: 'اقلب الاتجاه في النهاية للتنفس العميق، حافظ على ثبات الجذع',
      muscleActivation: ['الصدر', 'الكتف الأمامي'],
    ),
    Exercise(
      id: 'push_ups',
      nameAr: 'تمارين الضغط',
      nameEn: 'Push Ups',
      muscleGroup: 'صدر',
      secondaryMuscles: 'ترايسبس، كتف',
      difficulty: 'سهل',
      equipment: 'بدون جهاز',
      youtubeVideoId: 'IODxDxX7oi4',
      description: 'تمرين bodyweight أساسي للصدر',
      formTips: 'انزل حتى يصبح الكتف بموازاة المرفق، حافظ على جسم مستقيم',
      muscleActivation: ['الصدر', 'الترايسبس', 'الكتف'],
    ),
    Exercise(
      id: 'dips',
      nameAr: 'ديدز للصدر',
      nameEn: 'Chest Dips',
      muscleGroup: 'صدر',
      secondaryMuscles: 'ترايسبس، كتف',
      difficulty: 'متوسط',
      equipment: ' parallel bars',
      youtubeVideoId: '2z8JmcrW-As',
      description: 'تمرين متقدم للصدر باستخدام وزن الجسم',
      formTips: 'انحنِ قليلاً للأمام لاستهداف الصدر، حافظ على مرفقين متقاربين',
      muscleActivation: ['الصدر السفلي', 'الترايسبس'],
    ),
    Exercise(
      id: 'machine_chest_press',
      nameAr: 'ماكينة ضغط الصدر',
      nameEn: 'Machine Chest Press',
      muscleGroup: 'صدر',
      secondaryMuscles: 'ترايسبس',
      difficulty: 'سهل',
      equipment: 'ماكينة',
      youtubeVideoId: 'v3MjJvGTDJA',
      description: 'تمرين آمن على الماكينة لبناء الصدر',
      formTips: 'حافظ على الظهر مسطح against the pad، اضغط بشكل متحكم',
      muscleActivation: ['الصدر', 'الترايسبس'],
    ),

    // ═══════════════════════════════════════════════════════════
    // BACK EXERCISES
    // ═══════════════════════════════════════════════════════════
    Exercise(
      id: 'deadlift',
      nameAr: 'ديدlift',
      nameEn: 'Deadlift',
      muscleGroup: 'ظهر',
      secondaryMuscles: 'رجل خلفية، بطن، ترابيس',
      difficulty: 'متقدم',
      equipment: 'باربل',
      youtubeVideoId: 'op9kVnSso6Q',
      description: 'تمرين مركب كبير لبناء قوة الظهر الشاملة',
      formTips: 'حافظ على استقامة الظهر، الركبتان بزاوية صغيرة، اسحب بقوة',
      muscleActivation: ['الظهر الكامل', 'الرجل الخلفية', 'البطن'],
    ),
    Exercise(
      id: 'pull_ups',
      nameAr: 'بول أب',
      nameEn: 'Pull Ups',
      muscleGroup: 'ظهر',
      secondaryMuscles: 'بايسبس، ترابيس',
      difficulty: 'متوسط',
      equipment: 'pull-up bar',
      youtubeVideoId: 'eGo4IYlbE5g',
      description: 'تمرين bodyweight كلاسيكي للظهر',
      formTips: 'اسحب حتى تتجاوز الذقن البار، حافظ على استقامة الجذع',
      muscleActivation: ['الظهر العلوي', 'اللاتس', 'البايسبس'],
    ),
    Exercise(
      id: 'lat_pulldown',
      nameAr: 'لات بول داون',
      nameEn: 'Lat Pulldown',
      muscleGroup: 'ظهر',
      secondaryMuscles: 'بايسبس، ترابيس',
      difficulty: 'سهل',
      equipment: 'كيبل',
      youtubeVideoId: 'CAwfj1ng2SI',
      description: 'تمرين كيبل لاستهداف عضلات الظهر العريضة',
      formTips: 'اسحب نحو السرة، حافظ على استقامة الظهر، استخدم قوة الظهر',
      muscleActivation: ['الظهر العريض', 'اللاتس', 'البايسبس'],
    ),
    Exercise(
      id: 'seated_row',
      nameAr: 'سيتد راو',
      nameEn: 'Seated Cable Row',
      muscleGroup: 'ظهر',
      secondaryMuscles: 'بايسبس، ترابيس',
      difficulty: 'سهل',
      equipment: 'كيبل',
      youtubeVideoId: 'GZbfZ033f74',
      description: 'تمرين كيبل لعضلات الظهر الوسطى',
      formTips: 'اسحب نحو السرة، ادفع بالمرفقين للخلف، حافظ على استقامة الظهر',
      muscleActivation: ['الظهر الأوسط', 'الرات', 'البايسبس'],
    ),
    Exercise(
      id: 'bent_over_row',
      nameAr: 'بينت أوف راو',
      nameEn: 'Bent Over Row',
      muscleGroup: 'ظهر',
      secondaryMuscles: 'بايسبس، ترابيس',
      difficulty: 'متوسط',
      equipment: 'باربل',
      youtubeVideoId: 'vT2GjY_Umpw',
      description: 'تمرين بالباربل لاستهداف الظهر العلوي',
      formTips: 'حافظ على استقامة الظهر، الظهر موازٍ للأرض، اسحب للبطول',
      muscleActivation: ['الظهر العلوي', 'اللاتس', 'البايسبس'],
    ),
    Exercise(
      id: 'face_pulls',
      nameAr: 'فيرسايد بول',
      nameEn: 'Face Pulls',
      muscleGroup: 'ظهر',
      secondaryMuscles: 'كتف خلفي، ترابيس',
      difficulty: 'سهل',
      equipment: 'كيبل',
      youtubeVideoId: 'rep-qVOkqgk',
      description: 'تمرين كيبل لصحة الكتف والظهر',
      formTips: 'اسحب نحو الوجه وليس الصدر، ادفع بأعلى كتف',
      muscleActivation: ['الكتف الخلفي', 'الترابيس', 'الروات'],
    ),
    Exercise(
      id: 't_bar_row',
      nameAr: 'تي بار راو',
      nameEn: 'T-Bar Row',
      muscleGroup: 'ظهر',
      secondaryMuscles: 'بايسبس، ترابيس',
      difficulty: 'متوسط',
      equipment: 'T-bar',
      youtubeVideoId: 'j3Q7bS5kHPE',
      description: 'تمرين مركب لعضلات الظهر العريضة',
      formTips: 'حافظ على ثبات الجذع، اسحب للصدر مع ضغط لوح الكتف',
      muscleActivation: ['الظهر العريض', 'التراتس', 'البايسبس'],
    ),

    // ═══════════════════════════════════════════════════════════
    // SHOULDER EXERCISES
    // ═══════════════════════════════════════════════════════════
    Exercise(
      id: 'overhead_press',
      nameAr: 'أوفرهيد بريس',
      nameEn: 'Overhead Press',
      muscleGroup: 'أكتاف',
      secondaryMuscles: 'ترايسبس، ترابيس',
      difficulty: 'متوسط',
      equipment: 'باربل',
      youtubeVideoId: '2yjwXTZQDDI',
      description: 'تمرين أساسي لبناء أكتاف قوية',
      formTips: 'حافظ على مركزية الحركة، لا ترفع الحوض، اضغط للأعلى',
      muscleActivation: ['الكتف الأمامي', 'الكتف الجانبي', 'الترايسبس'],
    ),
    Exercise(
      id: 'lateral_raise',
      nameAr: 'لاتيرال ريز',
      nameEn: 'Lateral Raise',
      muscleGroup: 'أكتاف',
      secondaryMuscles: 'كتف خلفي',
      difficulty: 'سهل',
      equipment: 'دمبل',
      youtubeVideoId: '3VcKaXpzqRo',
      description: 'تمرين عزل للكتف الجانبي',
      formTips: 'ارفع حتى يصبح الكوع بموازاة الكتف، لا تستخدم زخم',
      muscleActivation: ['الكتف الجانبي', 'الكتف الأمامي'],
    ),
    Exercise(
      id: 'front_raise',
      nameAr: 'فرونت ريز',
      nameEn: 'Front Raise',
      muscleGroup: 'أكتاف',
      secondaryMuscles: 'كتف جانبي',
      difficulty: 'سهل',
      equipment: 'دمبل',
      youtubeVideoId: 'tD3B78F9lq8',
      description: 'تمرين عزل للكتف الأمامي',
      formTips: 'حافظ على شد البطن، تجنب التأرجح، ارفع بذراع واحد',
      muscleActivation: ['الكتف الأمامي', 'الكتف الجانبي'],
    ),
    Exercise(
      id: 'rear_delt_fly',
      nameAr: 'فيرسايد ريز خلفي',
      nameEn: 'Rear Delt Fly',
      muscleGroup: 'أكتاف',
      secondaryMuscles: 'ظهر علوي',
      difficulty: 'سهل',
      equipment: 'دمبل',
      youtubeVideoId: 'ssBo2DprNd0',
      description: 'تمرين عزل للكتف الخلفي',
      formTips: 'ادفع نحو الخلف بأعلى كتف، حافظ على انحناء خفيف في المرفقين',
      muscleActivation: ['الكتف الخلفي', 'الظهر العلوي'],
    ),
    Exercise(
      id: 'arnold_press',
      nameAr: 'أرنولد بريس',
      nameEn: 'Arnold Press',
      muscleGroup: 'أكتاف',
      secondaryMuscles: 'ترايسبس',
      difficulty: 'متوسط',
      equipment: 'دمبل',
      youtubeVideoId: '6Z15_WdXmVw',
      description: 'تمرين دمبل مركب للأكتاف مع تدوير',
      formTips: 'ابدأ بالكتف الجانبي، ادفع للأعلى مع التدوير، اقلب الحركة',
      muscleActivation: ['الكتف الأمامي', 'الكتف الجانبي', 'الترايسبس'],
    ),
    Exercise(
      id: 'shrugs',
      nameAr: 'شرجز',
      nameEn: 'Barbell Shrugs',
      muscleGroup: 'أكتاف',
      secondaryMuscles: 'ترابيس',
      difficulty: 'سهل',
      equipment: 'باربل',
      youtubeVideoId: 'lVEanOFuNY8',
      description: 'تمرين للترابيس وأعلى الظهر',
      formTips: 'ارفع الأكتاف للأعلى فقط، حافظ على استقامة الذراعين',
      muscleActivation: ['الترابيس', 'الكتف الخلفي'],
    ),
    Exercise(
      id: 'upright_row',
      nameAr: 'أبرايت راو',
      nameEn: 'Upright Row',
      muscleGroup: 'أكتاف',
      secondaryMuscles: 'ترابيس، بايسبس',
      difficulty: 'متوسط',
      equipment: 'باربل',
      youtubeVideoId: '',
      description: 'تمرين مركب للأكتاف والترابيس',
      formTips: 'اسحب البار沿着身体向上靠近 الذقن، حافظ على استقامة المعصم',
      muscleActivation: ['الكتف الجانبي', 'الترابيس', 'البايسبس'],
    ),

    // ═══════════════════════════════════════════════════════════
    // BICEPS EXERCISES
    // ═══════════════════════════════════════════════════════════
    Exercise(
      id: 'barbell_curl',
      nameAr: 'بار بريس كيرل',
      nameEn: 'Barbell Curl',
      muscleGroup: 'بايسبس',
      secondaryMuscles: 'ساعد',
      difficulty: 'سهل',
      equipment: 'باربل',
      youtubeVideoId: 'ykJmrZ5v0Oo',
      description: 'تمرين أساسي للبايسبس بالباربل',
      formTips: 'حافظ على ثبات المرفقين بجانب الجسم، لا تتأرجح الظهر',
      muscleActivation: ['البايسبس', 'الساعد'],
    ),
    Exercise(
      id: 'hammer_curl',
      nameAr: 'هامر كيرل',
      nameEn: 'Hammer Curl',
      muscleGroup: 'بايسبس',
      secondaryMuscles: 'ساعد',
      difficulty: 'سهل',
      equipment: 'دمبل',
      youtubeVideoId: 'zC3nLlEvin4',
      description: 'تمرين يستهدف الراس القصير للبايسبس',
      formTips: 'حافظ على راحة يد مقلوبة، استهدف الراس القصير',
      muscleActivation: ['البايسبس', 'البراكياليس'],
    ),
    Exercise(
      id: 'preacher_curl',
      nameAr: 'بريتشر كيرل',
      nameEn: 'Preacher Curl',
      muscleGroup: 'بايسبس',
      secondaryMuscles: 'ساعد',
      difficulty: 'سهل',
      equipment: 'بريتشر',
      youtubeVideoId: 'Ys2G8YG5gsc',
      description: 'تمرين عزل للبايسبس على البريتشر',
      formTips: 'اقلب الرسغ في النهاية، حافظ على استقامة الذراع',
      muscleActivation: ['البايسبس', 'الساعد'],
    ),
    Exercise(
      id: 'concentration_curl',
      nameAr: 'كونسنتريشن كيرل',
      nameEn: 'Concentration Curl',
      muscleGroup: 'بايسبس',
      secondaryMuscles: 'ساعد',
      difficulty: 'سهل',
      equipment: 'دمبل',
      youtubeVideoId: '0X3kT8V0enc',
      description: 'تمرين عزل للبايسبس بالتركيز',
      formTips: 'ركز على النزول البطيء، لا تحرك المرفق',
      muscleActivation: ['البايسبس'],
    ),
    Exercise(
      id: 'cable_curl',
      nameAr: 'كيبل كيرل',
      nameEn: 'Cable Curl',
      muscleGroup: 'بايسبس',
      secondaryMuscles: 'ساعد',
      difficulty: 'سهل',
      equipment: 'كيبل',
      youtubeVideoId: 'eGJj6bSrswA',
      description: 'تمرين كيبل للبايسبس مع توتر مستمر',
      formTips: 'حافظ على توتر مستمر طوال الحركة، لا تحرك المرفق',
      muscleActivation: ['البايسبس', 'الساعد'],
    ),
    Exercise(
      id: 'inclined_dumbbell_curl',
      nameAr: 'إنكلايند دمبل كيرل',
      nameEn: 'Incline Dumbbell Curl',
      muscleGroup: 'بايسبس',
      secondaryMuscles: 'ساعد',
      difficulty: 'متوسط',
      equipment: 'دمبل',
      youtubeVideoId: 'So_Ip4GcM5I',
      description: 'تمرين بايسبس على مقعد مائل للاستطالة',
      formTips: 'انحنِ للخلف على المقعد، اسمح للبايسبس بالاستطالة الكاملة',
      muscleActivation: ['البايسبس', 'الساعد'],
    ),

    // ═══════════════════════════════════════════════════════════
    // TRICEPS EXERCISES
    // ═══════════════════════════════════════════════════════════
    Exercise(
      id: 'close_grip_bench',
      nameAr: 'كلوز غريب بنش',
      nameEn: 'Close Grip Bench Press',
      muscleGroup: 'ترايسبس',
      secondaryMuscles: 'صدر، أكتاف',
      difficulty: 'متوسط',
      equipment: 'باربل',
      youtubeVideoId: 'HDDsXQbY4Ko',
      description: 'تمرين مركب للترايسبس مع تثبيت المرفقين',
      formTips: 'حافظ على مرفقين متقاربين، اضغط للأعلى بشكل متحكم',
      muscleActivation: ['الترايسبس', 'الصدر', 'الكتف'],
    ),
    Exercise(
      id: 'tricep_pushdown',
      nameAr: 'تراي ريز بوش داون',
      nameEn: 'Tricep Pushdown',
      muscleGroup: 'ترايسبس',
      secondaryMuscles: 'ساعد',
      difficulty: 'سهل',
      equipment: 'كيبل',
      youtubeVideoId: '2-LAMcpzODU',
      description: 'تمرين كيبل أساسي للترايسبس',
      formTips: 'انزل حتى زاوية 90 درجة ثم اضغط، حافظ على ثبات المرفق',
      muscleActivation: ['الترايسبس', 'الساعد'],
    ),
    Exercise(
      id: 'skull_crusher',
      nameAr: 'سكل كراشر',
      nameEn: 'Skull Crusher',
      muscleGroup: 'ترايسبس',
      secondaryMuscles: 'ساعد',
      difficulty: 'متوسط',
      equipment: 'E-Z بار',
      youtubeVideoId: 'd_KZxkY_0cM',
      description: 'تمرين متقدم للترايسبس على المقعد',
      formTips: 'انزل للبار نحو الجبهة بشكل متحكم، لا تفرقع المفصل',
      muscleActivation: ['الترايسبس'],
    ),
    Exercise(
      id: 'overhead_tricep',
      nameAr: 'أوفرهيد تراي ريز',
      nameEn: 'Overhead Tricep Extension',
      muscleGroup: 'ترايسبس',
      secondaryMuscles: 'ساعد',
      difficulty: 'سهل',
      equipment: 'دمبل',
      youtubeVideoId: '6k7PGZFBqTc',
      description: 'تمرين عزل للترايسبس فوق الرأس',
      formTips: 'حافظ على مرفق قريب من الرأس، انزل ببطء',
      muscleActivation: ['الترايسبس الطويل', 'الترايسبس الجانبي'],
    ),
    Exercise(
      id: 'tricep_dips',
      nameAr: 'ديدز للترايسبس',
      nameEn: 'Tricep Dips',
      muscleGroup: 'ترايسبس',
      secondaryMuscles: 'صدر، أكتاف',
      difficulty: 'متوسط',
      equipment: 'parallel bars',
      youtubeVideoId: '2z8JmcrW-As',
      description: 'تمرين bodyweight للترايسبس',
      formTips: 'انزل بزاوية 90 درجة، حافظ على مرفقين متقاربين',
      muscleActivation: ['الترايسبس', 'الصدر'],
    ),
    Exercise(
      id: 'kickbacks',
      nameAr: 'كيك باكس',
      nameEn: 'Tricep Kickbacks',
      muscleGroup: 'ترايسبس',
      secondaryMuscles: 'ساعد',
      difficulty: 'سهل',
      equipment: 'دمبل',
      youtubeVideoId: 'Z6t22iHt6aM',
      description: 'تمرين عزل للترايسبس مع س-extension',
      formTips: 'حافظ على استقامة الظهر، kickback ببطء',
      muscleActivation: ['الترايسبس'],
    ),

    // ═══════════════════════════════════════════════════════════
    // LEGS EXERCISES
    // ═══════════════════════════════════════════════════════════
    Exercise(
      id: 'squat',
      nameAr: 'سكوات',
      nameEn: 'Barbell Squat',
      muscleGroup: 'رجل',
      secondaryMuscles: 'بطن، رجل خلفية، ألوية',
      difficulty: 'متوسط',
      equipment: 'باربل',
      youtubeVideoId: 'ultWZbUMPL8',
      description: 'تمرين ملك الرين لعضلات الرجل الكاملة',
      formTips: 'حافظ على استقامة الظهر، القدم بعرض الكتف، انزل لزاوية 90',
      muscleActivation: ['الفخذ الأمامي', 'الألوية', 'الرجل الخلفية'],
    ),
    Exercise(
      id: 'leg_press',
      nameAr: 'ليج بريس',
      nameEn: 'Leg Press',
      muscleGroup: 'رجل',
      secondaryMuscles: 'ألوية، رجل خلفية',
      difficulty: 'سهل',
      equipment: 'ماكينة',
      youtubeVideoId: 'IZxyjW7MPJQ',
      description: 'تمرين آمن على الماكينة للساقين',
      formTips: 'انزل حتى زاوية 90 درجة، حافظ على قدم مسطحة',
      muscleActivation: ['الفخذ الأمامي', 'الألوية'],
    ),
    Exercise(
      id: 'romanian_deadlift',
      nameAr: 'رومانيان ديدlift',
      nameEn: 'Romanian Deadlift',
      muscleGroup: 'رجل',
      secondaryMuscles: 'ظهر سفلي، ألوية',
      difficulty: 'متوسط',
      equipment: 'باربل',
      youtubeVideoId: 'JCXUYuzwNrM',
      description: 'تمرين لاستهداف الرجل الخلفية والألوية',
      formTips: 'انحنِ من الورك not الظهر، حافظ على ركبتين مثنيتين قليلاً',
      muscleActivation: ['الرجل الخلفية', 'الألوية', 'الظهر السفلي'],
    ),
    Exercise(
      id: 'leg_curl',
      nameAr: 'ليج كيرل',
      nameEn: 'Leg Curl',
      muscleGroup: 'رجل',
      secondaryMuscles: 'ساق',
      difficulty: 'سهل',
      equipment: 'ماكينة',
      youtubeVideoId: 'ELOCsoDSmrg',
      description: 'تمرين عزل للرجل الخلفية',
      formTips: 'حرك ببطء للتحكم، اقلب القدم للنهاية',
      muscleActivation: ['الرجل الخلفية'],
    ),
    Exercise(
      id: 'leg_extension',
      nameAr: 'ليج أكستنشن',
      nameEn: 'Leg Extension',
      muscleGroup: 'رجل',
      secondaryMuscles: 'ساق',
      difficulty: 'سهل',
      equipment: 'ماكينة',
      youtubeVideoId: '8iPEnn-lzCQ',
      description: 'تمرين عزل للفخذ الأمامي',
      formTips: 'ركز على الانقباض في الأعلى، لا تستخدم زخم',
      muscleActivation: ['الفخذ الأمامي'],
    ),
    Exercise(
      id: 'lunges',
      nameAr: 'لينجز',
      nameEn: 'Lunges',
      muscleGroup: 'رجل',
      secondaryMuscles: 'ألوية، بطن',
      difficulty: 'سهل',
      equipment: 'دمبل',
      youtubeVideoId: 'QOVGHTzWwUc',
      description: 'تمرين منفرد للرجل مع خطوة',
      formTips: 'حافظ على قدم أمامية مستقيمة، انزل حتى كلا الركبتين 90',
      muscleActivation: ['الفخذ الأمامي', 'الألوية', 'البطن'],
    ),
    Exercise(
      id: 'calf_raise',
      nameAr: 'كاف ريز',
      nameEn: 'Calf Raises',
      muscleGroup: 'رجل',
      secondaryMuscles: 'ساق',
      difficulty: 'سهل',
      equipment: 'ماكينة',
      youtubeVideoId: 'gwLzBJYoWlI',
      description: 'تمرين لعضلات الساق السفلية',
      formTips: 'انزل على الكعب وليس أطراف الأصابع، استعمل كامل المدى',
      muscleActivation: ['السمانة', 'الساق'],
    ),
    Exercise(
      id: 'hip_thrust',
      nameAr: 'هيبثراست',
      nameEn: 'Hip Thrust',
      muscleGroup: 'رجل',
      secondaryMuscles: 'أليوية، بطن',
      difficulty: 'سهل',
      equipment: 'باربل',
      youtubeVideoId: 'SEdqd1n0cvg',
      description: 'تمرين مركب للأليوية',
      formTips: 'ادفع من العقب not الأصابع، حافظ على استقامة الظهر',
      muscleActivation: ['الأليوية', 'الرجل الخلفية'],
    ),
    Exercise(
      id: 'bulgarian_split_squat',
      nameAr: 'بلقارين سبليت سكوات',
      nameEn: 'Bulgarian Split Squat',
      muscleGroup: 'رجل',
      secondaryMuscles: 'ألوية، بطن',
      difficulty: 'متوسط',
      equipment: 'دمبل',
      youtubeVideoId: 'ot_to51gG8M',
      description: 'تمرين прогрессия للساق على خطوة',
      formTips: 'حافظ على قدم أمامية مستقيمة، قدم خلفية على مقعد',
      muscleActivation: ['الفخذ الأمامي', 'الأليوية', 'البطن'],
    ),

    // ═══════════════════════════════════════════════════════════
    // ABS EXERCISES
    // ═══════════════════════════════════════════════════════════
    Exercise(
      id: 'plank',
      nameAr: 'بلانك',
      nameEn: 'Plank',
      muscleGroup: 'بطن',
      secondaryMuscles: 'كتف، ظهر',
      difficulty: 'سهل',
      equipment: 'بدون',
      youtubeVideoId: 'ASdvN_XEl_c',
      description: 'تمرين ايزومتري للبطن整体',
      formTips: 'حافظ على خط مستقيم من الرأس للقدمين، لا ترفع أو تنزل الحوض',
      muscleActivation: ['البطن المستعرض', 'البطن المستقيم', 'الكتف'],
    ),
    Exercise(
      id: 'crunches',
      nameAr: 'كرانش',
      nameEn: 'Crunches',
      muscleGroup: 'بطن',
      secondaryMuscles: 'بطن مائل',
      difficulty: 'سهل',
      equipment: 'بدون',
      youtubeVideoId: 'Xyd_fa5zoEU',
      description: 'تمرين كلاسيكي للبطن',
      formTips: 'لا تسحب الرقبة، استعمل البطن not الذراعين',
      muscleActivation: ['البطن المستقيم', 'البطن المائل'],
    ),
    Exercise(
      id: 'leg_raises',
      nameAr: 'ليج ريزز',
      nameEn: 'Leg Raises',
      muscleGroup: 'بطن',
      secondaryMuscles: 'بطن سفلي',
      difficulty: 'متوسط',
      equipment: 'بدون',
      youtubeVideoId: 'l4kQd9H3H1I',
      description: 'تمرين للبطن السفلي',
      formTips: 'انزل ببطء ولا تلمس الأرض، حافظ على ساقي مستقيمتين',
      muscleActivation: ['البطن السفلي', 'الحرقفية'],
    ),
    Exercise(
      id: 'russian_twist',
      nameAr: 'روسين تويست',
      nameEn: 'Russian Twist',
      muscleGroup: 'بطن',
      secondaryMuscles: 'بطن مائل',
      difficulty: 'سهل',
      equipment: 'دمبل',
      youtubeVideoId: 'wkD8rjkodUI',
      description: 'تمرين للدوران للبطن المائل',
      formTips: 'حافظ على قدميك مرفوعة، اسمح للجسم بالدوران',
      muscleActivation: ['البطن المائل', 'البطن المستقيم'],
    ),
    Exercise(
      id: 'mountain_climber',
      nameAr: 'ماونتن كلمبر',
      nameEn: 'Mountain Climbers',
      muscleGroup: 'بطن',
      secondaryMuscles: 'صدر، كتف',
      difficulty: 'متوسط',
      equipment: 'بدون',
      youtubeVideoId: 'nmwgirgXLYM',
      description: 'تمرين حركي للبطن مع كارديو',
      formTips: 'حافظ على استقامة الظهر، alternate بسرعة',
      muscleActivation: ['البطن', 'الكتف', 'الصدر'],
    ),
    Exercise(
      id: 'ab_wheel_rollout',
      nameAr: 'اب ويل رول',
      nameEn: 'Ab Wheel Rollout',
      muscleGroup: 'بطن',
      secondaryMuscles: 'ظهر، كتف',
      difficulty: 'متقدم',
      equipment: 'اب ويل',
      youtubeVideoId: 'twR2j3lDyrk',
      description: 'تمرين متقدم للبطن整体',
      formTips: 'انزل ببطء، حافظ على استقامة الظهر، لا تلمس الأرض',
      muscleActivation: ['البطن المستقيم', 'الظهر', 'الكتف'],
    ),
    Exercise(
      id: 'hanging_leg_raise',
      nameAr: 'هانكنغ ليج ريز',
      nameEn: 'Hanging Leg Raise',
      muscleGroup: 'بطن',
      secondaryMuscles: 'بطن سفلي',
      difficulty: 'متقدم',
      equipment: 'pull-up bar',
      youtubeVideoId: 'hdng3Nm1x_E',
      description: 'تمرين متقدم للبطن المعلق',
      formTips: 'ارفع ساقيك للأعلى ببطء، حافظ على استقامة الجسم',
      muscleActivation: ['البطن السفلي', 'البطن المستقيم'],
    ),

    // ═══════════════════════════════════════════════════════════
    // CARDIO EXERCISES
    // ═══════════════════════════════════════════════════════════
    Exercise(
      id: 'treadmill_run',
      nameAr: 'جري على treadmill',
      nameEn: 'Treadmill Running',
      muscleGroup: 'كارديو',
      secondaryMuscles: 'رجل',
      difficulty: 'متوسط',
      equipment: 'treadmill',
      youtubeVideoId: '8iPEnn-lzCQ',
      description: 'جري خفيف على السير المتحرك',
      formTips: 'حافظ على معدل نبض مناسب، ابدأ ببطء',
      muscleActivation: ['القلب', 'الرجل'],
    ),
    Exercise(
      id: 'jump_rope',
      nameAr: 'نط الحبل',
      nameEn: 'Jump Rope',
      muscleGroup: 'كارديو',
      secondaryMuscles: 'كتف، ساق',
      difficulty: 'متوسط',
      equipment: 'حبل',
      youtubeVideoId: 'FJmRQ5iTXKE',
      description: 'تمرين كارديو عالي الكثافة',
      formTips: 'هبط على أطراف الأصابع، حافظ على مرفقين قريبين من الجسم',
      muscleActivation: ['القلب', 'الساق', 'الكتف'],
    ),
    Exercise(
      id: 'burpees',
      nameAr: 'بيربي',
      nameEn: 'Burpees',
      muscleGroup: 'كارديو',
      secondaryMuscles: 'صدر، رجل، بطن',
      difficulty: 'متقدم',
      equipment: 'بدون',
      youtubeVideoId: 'TU8QYVW0gDU',
      description: 'تمرين كارديو مركب whole body',
      formTips: 'حافظ على شكل صحيح في كل position، استرح عند الحاجة',
      muscleActivation: ['القلب', 'الصدر', 'الرجل', 'البطن'],
    ),
    Exercise(
      id: 'high_knees',
      nameAr: 'هاي نيز',
      nameEn: 'High Knees',
      muscleGroup: 'كارديو',
      secondaryMuscles: 'بطن، رجل',
      difficulty: 'سهل',
      equipment: 'بدون',
      youtubeVideoId: 'D0qLvHAFqLU',
      description: 'تمرين كارديو مع رفع الركب',
      formTips: 'ارفع الركبتين حتى مستوى الحوض، حافظ على سرعة',
      muscleActivation: ['القلب', 'البطن', 'الرجل'],
    ),
    Exercise(
      id: 'jumping_jacks',
      nameAr: 'جامبينج جاكس',
      nameEn: 'Jumping Jacks',
      muscleGroup: 'كارديو',
      secondaryMuscles: 'كتف، رجل',
      difficulty: 'سهل',
      equipment: 'بدون',
      youtubeVideoId: 'c4DAnQ6DtF8',
      description: 'تمرين كارديو بسيط Whole body',
      formTips: 'استعمل الذراعين للمساعدة، حافظ على ساقين مستقيمتين',
      muscleActivation: ['القلب', 'الكتف', 'الرجل'],
    ),
    Exercise(
      id: 'elliptical',
      nameAr: 'آلة بيضاوية',
      nameEn: 'Elliptical Trainer',
      muscleGroup: 'كارديو',
      secondaryMuscles: 'رجل، كتف',
      difficulty: 'سهل',
      equipment: 'آلة بيضاوية',
      youtubeVideoId: 'J9L8cRPj2p8',
      description: 'تمرين كارديو منخفض التأثير',
      formTips: 'حافظ على سرعة ثابتة، استعمل المقبض للمساعدة',
      muscleActivation: ['القلب', 'الرجل', 'الكتف'],
    ),
  ];

  static List<Exercise> getByMuscle(String muscle) {
    return allExercises
        .where((e) => e.muscleGroup == muscle)
        .toList();
  }

  static Exercise? getById(String id) {
    try {
      return allExercises.firstWhere((e) => e.id == id);
    } catch (_) {
      return null;
    }
  }

  static List<Exercise> getByDifficulty(String difficulty) {
    return allExercises
        .where((e) => e.difficulty == difficulty)
        .toList();
  }

  static List<Exercise> getByEquipment(String equipment) {
    return allExercises
        .where((e) => e.equipment.toLowerCase().contains(equipment.toLowerCase()))
        .toList();
  }
}
