import 'package:flutter/material.dart';
import '../../../../theme/app_text.dart';
import '../../data/repositories/coach_repository_impl.dart';
import '../../domain/entities/coach_entity.dart';
import '../widgets/coach_shared.dart';
import 'coach_dashboard_screen.dart';
import '../providers/coach_dashboard_providers.dart';

const _kSpecializations = [
  'weight loss',
  'muscle gain',
  'nutrition',
  'strength',
  'cardio',
  'flexibility',
  'crossfit',
  'yoga',
  'pilates',
];

class CoachRegistrationScreen extends StatefulWidget {
  const CoachRegistrationScreen({super.key});

  @override
  State<CoachRegistrationScreen> createState() => _CoachRegistrationScreenState();
}

class _CoachRegistrationScreenState extends State<CoachRegistrationScreen> {
  final _formKey = GlobalKey<FormState>();
  final _bioController = TextEditingController();
  final _priceController = TextEditingController();
  final _stripeController = TextEditingController();

  final List<String> _selectedSpecs = [];
  bool _isLoading = false;
  String? _error;

  @override
  void dispose() {
    _bioController.dispose();
    _priceController.dispose();
    _stripeController.dispose();
    super.dispose();
  }

  Future<void> _register() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedSpecs.isEmpty) {
      setState(() => _error = 'Please select at least one specialization');
      return;
    }

    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      final repository = CoachRepositoryImpl();

      final coach = CoachEntity(
        id: '', // Will be generated by Supabase
        userId: '', // Will be set from auth
        bio: _bioController.text.trim(),
        priceMonthly: double.parse(_priceController.text),
        specialization: _selectedSpecs,
        rating: 0.0, // New coaches start with 0 rating
        isActive: true,
        stripeAccountId: _stripeController.text.trim().isEmpty
            ? null
            : _stripeController.text.trim(),
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await repository.createCoachProfile(coach);

      if (!mounted) return;

      // Show success message
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Welcome to CoreGym Coaches!'),
          backgroundColor: Colors.green,
        ),
      );

      // Navigate to coach dashboard
      Navigator.of(context).pushAndRemoveUntil(
        MaterialPageRoute(
          builder: (_) => CoachDashboardProviders.provideAll(
            child: const CoachDashboardScreen(),
          ),
        ),
        (route) => false,
      );
    } catch (e) {
      setState(() {
        _error = e.toString();
        _isLoading = false;
      });
    }
  }

  void _toggleSpec(String spec) {
    setState(() {
      if (_selectedSpecs.contains(spec)) {
        _selectedSpecs.remove(spec);
      } else {
        _selectedSpecs.add(spec);
      }
      _error = null;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: kCoachBg,
      body: SafeArea(
        child: CustomScrollView(
          slivers: [
            _buildAppBar(),
            _buildForm(),
          ],
        ),
      ),
    );
  }

  Widget _buildAppBar() {
    return SliverToBoxAdapter(
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                GestureDetector(
                  onTap: () => Navigator.pop(context),
                  child: Container(
                    padding: const EdgeInsets.all(8),
                    decoration: BoxDecoration(
                      color: kCoachCard,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: const Icon(Icons.arrow_back_rounded,
                        color: Colors.white, size: 20),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Text(
                    'BECOME A COACH',
                    style: AppText.labelLg.copyWith(
                      color: Colors.white,
                      letterSpacing: 1.5,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 24),
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [
                    kCoachGold.withValues(alpha: 0.2),
                    kCoachGold.withValues(alpha: 0.05),
                  ],
                ),
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: kCoachGold.withValues(alpha: 0.3)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.all(10),
                        decoration: BoxDecoration(
                          color: kCoachGold.withValues(alpha: 0.2),
                          shape: BoxShape.circle,
                        ),
                        child: const Icon(
                          Icons.workspace_premium_rounded,
                          color: kCoachGold,
                          size: 24,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Join Our Coach Network',
                              style: AppText.bodyLg.copyWith(
                                color: Colors.white,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                            Text(
                              'Share your expertise and help others achieve their fitness goals',
                              style: AppText.bodySm.copyWith(
                                color: kCoachMuted,
                                height: 1.4,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildForm() {
    return SliverToBoxAdapter(
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 20),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Bio Section
              Text(
                'ABOUT YOU',
                style: AppText.labelMd.copyWith(
                  color: kCoachMuted,
                  letterSpacing: 1.5,
                ),
              ),
              const SizedBox(height: 12),
              _buildTextField(
                controller: _bioController,
                hint: 'Tell us about your fitness background and coaching philosophy...',
                maxLines: 4,
                validator: (v) {
                  if (v == null || v.trim().isEmpty) {
                    return 'Bio is required';
                  }
                  if (v.length < 50) {
                    return 'Bio must be at least 50 characters';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 24),

              // Specializations Section
              Text(
                'SPECIALIZATIONS',
                style: AppText.labelMd.copyWith(
                  color: kCoachMuted,
                  letterSpacing: 1.5,
                ),
              ),
              const SizedBox(height: 12),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: _kSpecializations.map((spec) {
                  final isSelected = _selectedSpecs.contains(spec);
                  return _buildSpecChip(spec, isSelected);
                }).toList(),
              ),
              const SizedBox(height: 24),

              // Price Section
              Text(
                'MONTHLY PRICE (USD)',
                style: AppText.labelMd.copyWith(
                  color: kCoachMuted,
                  letterSpacing: 1.5,
                ),
              ),
              const SizedBox(height: 12),
              _buildTextField(
                controller: _priceController,
                hint: 'e.g., 99.99',
                keyboardType: TextInputType.number,
                prefixIcon: Icons.attach_money_rounded,
                validator: (v) {
                  if (v == null || v.isEmpty) {
                    return 'Price is required';
                  }
                  final price = double.tryParse(v);
                  if (price == null || price <= 0) {
                    return 'Enter a valid price';
                  }
                  if (price < 10) {
                    return 'Minimum price is \$10';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 24),

              // Stripe Section (Optional)
              Text(
                'STRIPE ACCOUNT ID (OPTIONAL)',
                style: AppText.labelMd.copyWith(
                  color: kCoachMuted,
                  letterSpacing: 1.5,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Connect your Stripe account to receive payments',
                style: AppText.bodySm.copyWith(color: kCoachSubtle),
              ),
              const SizedBox(height: 12),
              _buildTextField(
                controller: _stripeController,
                hint: 'acct_xxxxxxxxxx',
                prefixIcon: Icons.account_balance_wallet_outlined,
              ),
              const SizedBox(height: 32),

              // Error Message
              if (_error != null)
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(16),
                  margin: const EdgeInsets.only(bottom: 16),
                  decoration: BoxDecoration(
                    color: const Color(0x33FF7351),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(color: const Color(0xFFFF7351)),
                  ),
                  child: Row(
                    children: [
                      const Icon(
                        Icons.error_outline_rounded,
                        color: Color(0xFFFF7351),
                        size: 20,
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          _error!,
                          style: AppText.bodySm.copyWith(
                            color: const Color(0xFFFF7351),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),

              // Submit Button
              SizedBox(
                width: double.infinity,
                height: 56,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _register,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: kCoachGold,
                    foregroundColor: Colors.black,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                    ),
                    elevation: 0,
                  ),
                  child: _isLoading
                      ? const SizedBox(
                          width: 24,
                          height: 24,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.black,
                          ),
                        )
                      : Text(
                          'COMPLETE REGISTRATION',
                          style: AppText.buttonPrimary.copyWith(
                            color: Colors.black,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'By registering, you agree to our Terms of Service and Coach Agreement',
                textAlign: TextAlign.center,
                style: AppText.bodySm.copyWith(
                  color: kCoachSubtle,
                  fontSize: 11,
                ),
              ),
              const SizedBox(height: 40),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String hint,
    int maxLines = 1,
    TextInputType? keyboardType,
    IconData? prefixIcon,
    String? Function(String?)? validator,
  }) {
    return TextFormField(
      controller: controller,
      maxLines: maxLines,
      keyboardType: keyboardType,
      style: AppText.bodyMd.copyWith(color: Colors.white),
      validator: validator,
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: AppText.bodyMd.copyWith(color: kCoachSubtle),
        prefixIcon: prefixIcon != null
            ? Icon(prefixIcon, color: kCoachMuted, size: 20)
            : null,
        filled: true,
        fillColor: kCoachCard,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: kCoachGold, width: 1.5),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: Color(0xFFFF7351), width: 1),
        ),
        focusedErrorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: Color(0xFFFF7351), width: 1.5),
        ),
        contentPadding: const EdgeInsets.all(16),
      ),
    );
  }

  Widget _buildSpecChip(String spec, bool isSelected) {
    return GestureDetector(
      onTap: () => _toggleSpec(spec),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
        decoration: BoxDecoration(
          color: isSelected
              ? kCoachGold.withValues(alpha: 0.2)
              : kCoachCard,
          borderRadius: BorderRadius.circular(8),
          border: Border.all(
            color: isSelected ? kCoachGold : kCoachBorder,
            width: isSelected ? 1.5 : 1,
          ),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            if (isSelected)
              const Icon(
                Icons.check_rounded,
                color: kCoachGold,
                size: 14,
              ),
            if (isSelected) const SizedBox(width: 6),
            Text(
              spec.toUpperCase(),
              style: AppText.labelMd.copyWith(
                color: isSelected ? kCoachGold : kCoachMuted,
                letterSpacing: 0.5,
                fontSize: 11,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
